### ISSUE TITLE
Cannot set properties of undefined (setting 'toggle')

### ISSUE THREAD

**Issue by abdifatahmuse** [fkhadra/react-toastify#1139]
**report a *bug*?**

**What is the current behavior?**

 Console
```js
TypeError: Cannot set properties of undefined (setting 'toggle')
    at Object.setToggle (react-toastify.esm.mjs:2:4002)
    at Nle (react-toastify.esm.mjs:2:5676)
    at jle (react-toastify.esm.mjs:2:11639)
    at jg (react-dom.development.js:15486:18)
    at OR (react-dom.development.js:19617:20)
    at n$ (react-dom.development.js:21640:16)
    at iO (react-dom.development.js:27465:14)
    at F$ (react-dom.development.js:26596:12)
    at kre (react-dom.development.js:26505:5)
    at vS (react-dom.development.js:26473:7)
    at eO (react-dom.development.js:25889:20)
    at P$ (react-dom.development.js:26135:20)
    at ad (react-dom.development.js:12042:22)
    at react-dom.development.js:25690:13
```

**I'm using like this **

**ToastHelper.ts**

```typescript
export default function CustomToast({
  title,
  isLoading,
  isDismiss = true,
  type,
}: {
  title: string;
  isLoading?: boolean;
  isDismiss?: boolean;
  type?: "info" | "success" | "warning" | "error" | "default";
}) {
  if (toast == undefined) return;

  if (isDismiss) toast.dismiss();

  if (IsNullOrWhiteSpace(title) || title == "undefined") {
    toast.dismiss();
    return;
  }

  return toast(title ?? "", {
    autoClose: 1100,
    draggable: true,
    theme: "colored",
    closeOnClick: true,
    pauseOnHover: true,
    progress: undefined,
    isLoading: isLoading,
    position: "top-right",
    hideProgressBar: false,
    type: type || "default",
    transition: Bounce,
  });
}
```

Call

```typescript
 CustomToast({
        title: "recorded successfully".capitalize(),
        isLoading: false,
        type: "success",
      });
```

**Comment by maazu** [comment]
This issue is already reported here: please check here https://github.com/fkhadra/react-toastify/issues/1051#issuecomment-2262875536
