### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'useLayoutEffect') when using UMD version and Babel

### ISSUE THREAD

**Issue by b0rek** [fkhadra/react-toastify#1167]
**Bug when using UMD version and Babel**

Windows 11
Google Chrome Version 129.0.6668.100 (Official Build) (64-bit)
Microsoft Edge for Business Version 129.0.2792.89 (Official build) (64-bit)

Error:
Uncaught TypeError: Cannot read properties of undefined (reading 'useLayoutEffect')
    at toast.ts:426:34
    at react-toastify.umd.js:1:188
    at react-toastify.umd.js:1:233 
  | (anonymous) | @ | toast.ts:426
  | (anonymous) | @ | react-toastify.umd.js:1
  | (anonymous) | @ | react-toastify.umd.js:1

Example to reproduce:
https://codesandbox.io/p/sandbox/react-toastify-umd-cdn-error-3c22gc

```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>React Toastify with CDN</title>

  <!-- React and ReactDOM (React v17) -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/18.2.0/umd/react.development.js" integrity="sha512-m7nhpWHotpucPI37I4lPovL28Bm2BhAMV8poF3F8Z9oOEZ3jlxGzkgvG0EMt1mVL1xydr1erlBbmN90js/ssUw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react-dom/18.2.0/umd/react-dom.development.min.js" integrity="sha512-I5GJQRKGdj2miDs8ComgARfiAQiZJo/43YasH22qtweoG+YRXLTDYegxC/vPgw/ERxRzww/F4l4+8UiMmI20sw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react-transition-group/4.4.5/react-transition-group.min.js" integrity="sha512-M5QLNrrxNshlQ6ojJ9/dHZubP5LbfRZaxYaGgmO10rp9SQOEAmlQejEKmTbH5S2laW8StxhqnN/tt065f9oJjw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  
  <!-- Babel for JSX transformation -->
  <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
  
  <!-- React Toastify v8 from CDN -->
<script src="https://cdn.jsdelivr.net/npm/react-toastify@10.0.6/dist/react-toastify.umd.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/react-toastify@10.0.6/dist/ReactToastify.min.css"/>

</head>
<body>
  <div id="root"></div>

  <script type="text/babel">
    const { ToastContainer, toast } = window['ReactToastify'];

    const App = () => {
      const showToast = () => {
        toast('Hello from React Toastify!');
      };

      return (
        <div>
          <h1>React Toastify Example</h1>
          <button onClick={showToast}>Show Toast</button>
          <ToastContainer />
        </div>
      );
    };

    // Render the App component into the #root div
    ReactDOM.render(<App />, document.getElementById('root'));
  </script>
</body>
</html>

```

**Comment by fkhadra** [comment]
I'm closing the issue as I'm planning to drop UMD support for the next version. Hope you understand
