### ISSUE TITLE
"npm start" get error

### ISSUE THREAD

**Issue by ilovefafa** [fkhadra/react-toastify#233]
### step:
1. npm install
2. npm start
3. get the following error.

the main error is **TypeError: Patterns must be a string or an array of string**,i think is the postcss error,and i find [postcss-cli issuse](https://github.com/postcss/postcss-cli/issues/212) said that it doesnt't have an option 'b'?i don't understand.

```
PS C:\Users\Administrator\Desktop\github-items\1-MyItems\react-ele-imitation\src\react-toastify-master> npm start

> react-toastify@4.3.0 start C:\Users\Administrator\Desktop\github-items\1-MyItems\react-ele-imitation\src\react-toastify-master
> npm run sass && webpack-dev-server --config ./webpack.config.dev.js


> react-toastify@4.3.0 sass C:\Users\Administrator\Desktop\github-items\1-MyItems\react-ele-imitation\src\react-toastify-master
> node-sass scss/main.scss dist/ReactToastify.css

Rendering Complete, saving .css file...
Wrote CSS to C:\Users\Administrator\Desktop\github-items\1-MyItems\react-ele-imitation\src\react-toastify-master\dist\ReactToastify.css

> react-toastify@4.3.0 postsass C:\Users\Administrator\Desktop\github-items\1-MyItems\react-ele-imitation\src\react-toastify-master
> postcss --use autoprefixer -m -b 'last 2 versions' dist/ReactToastify.css -o dist/ReactToastify.css

TypeError: Patterns must be a string or an array of strings
    at assertPatternsInput (C:\Users\Administrator\Desktop\github-items\1-MyItems\react-ele-imitation\src\react-toastify-master\node_modules\postcss-cli\node_modules\globby\index.js:14:9)
    at generateGlobTasks (C:\Users\Administrator\Desktop\github-items\1-MyItems\react-ele-imitation\src\react-toastify-master\node_modules\postcss-cli\node_modules\globby\index.js:20:2)
    at module.exports (C:\Users\Administrator\Desktop\github-items\1-MyItems\react-ele-imitation\src\react-toastify-master\node_modules\postcss-cli\node_modules\globby\index.js:67:15)
    at Promise.resolve.then (C:\Users\Administrator\Desktop\github-items\1-MyItems\react-ele-imitation\src\react-toastify-master\node_modules\postcss-cli\index.js:53:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-toastify@4.3.0 postsass: `postcss --use autoprefixer -m -b 'last 2 versions' dist/ReactToastify.css -o dist/ReactToastify.css`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-toastify@4.3.0 postsass script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-09-09T13_47_21_653Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-toastify@4.3.0 start: `npm run sass && webpack-dev-server --config ./webpack.config.dev.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-toastify@4.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-09-09T13_47_21_701Z-debug.log
```
thanks for answering my questions.

**Comment by fkhadra** [comment]
Hey @ilovefafa,

I checked the source of `postcss-cli` and indeed the option `-b` doesn't exist. 
I don't know why on linux or osx(the main os I work with) I didn't had the issue. Anyway, I fixed the issue by publishing a new release. Thanks for sharing the error.

**Comment by rayjencode** [comment]
i replace -b to -m still error exist x.x

**Comment by BlazFin** [comment]
The only way it worked for me:
`postcss --use autoprefixer -m \"last 10 versions\" css/style.concat.css -o css/style.prefix.css`
