### ISSUE TITLE
new react-transition-group version (4.4.0) causes error

### ISSUE THREAD

**Issue by itsmylife** [fkhadra/react-toastify#465]
**Do you want to request a *feature* or report a *bug*?**
It is a bug.

**What is the current behavior?**
When you freshly install the react-toastify it grabs the latest version of react-transition-group. Because its version is defined in package.json as `^4`. react-transition-group has a new release https://github.com/reactjs/react-transition-group/releases/tag/v4.4.0
When I use it before that release everything was fine. And after that release new installs produces problems. That is the error I am having:
```
[ error ] ReferenceError: Element is not defined
    at Object.<anonymous> (/Users/..../node_modules/react-transition-group/cjs/Transition.js:452:44)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/..../node_modules/react-transition-group/cjs/CSSTransition.js:14:42)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/ismailsimsek/Documents/olympuz/zcp_next/node_modules/react-transition-group/cjs/index.js:6:45)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

`npm install --save react-toastify`
use the toastify somewhere in your app
run your app and see the error

**What is the expected behavior?**
There should not be any error.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.13.0
NextJS 9.3.1
Browser does not matter. Alwasy error
It was working with the previous version of react-transition-group. Since it is not in my lock file it grabs the latest one and I am having the issue.

**Comment by KempfCreative** [comment]
This is blocking our builds as well.

**Comment by itsmylife** [comment]
That issue was gone by that release of react-transition-group:
https://github.com/reactjs/react-transition-group/releases/tag/v4.4.1
Apparently it is related to react-transition-group itself.
We can close that issue.
