### ISSUE TITLE
Warning: React does not recognize the `closeToast` prop on a DOM element

### ISSUE THREAD

**Issue by lokomass** [fkhadra/react-toastify#816]
Hello,

I want to use component in a toast, It works but I have this issues :

```
Warning: React does not recognize the `closeToast` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `closetoast` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at div
    at CircularProgress (https://dmf344.csb.app/node_modules/@material-ui/core/esm/CircularProgress/CircularProgress.js:88:23)
    at WithStyles (https://dmf344.csb.app/node_modules/@material-ui/styles/esm/withStyles/withStyles.js:47:31)
    at div
    at div
    at div
    at eval (https://dmf344.csb.app/node_modules/react-toastify/dist/react-toastify.js:1:1173)
    at L (https://dmf344.csb.app/node_modules/react-toastify/dist/react-toastify.js:1:12239)
    at div
    at div
    at eval (https://dmf344.csb.app/node_modules/react-toastify/dist/react-toastify.js:1:14184)
    at div
    at App
Warning: React does not recognize the `toastProps` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `toastprops` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at div
    at CircularProgress (https://dmf344.csb.app/node_modules/@material-ui/core/esm/CircularProgress/CircularProgress.js:88:23)
    at WithStyles (https://dmf344.csb.app/node_modules/@material-ui/styles/esm/withStyles/withStyles.js:47:31)
    at div
    at div
    at div
    at eval (https://dmf344.csb.app/node_modules/react-toastify/dist/react-toastify.js:1:1173)
    at L (https://dmf344.csb.app/node_modules/react-toastify/dist/react-toastify.js:1:12239)
    at div
    at div
    at eval (https://dmf344.csb.app/node_modules/react-toastify/dist/react-toastify.js:1:14184)
    at div
    at App
```

Here is my code :

https://codesandbox.io/s/fervent-butterfly-dmf344?file=/src/App.js

Thanks for your help

**Comment by fkhadra** [comment]
Hey @lokomass, wrap your component as follow
```js
export function print_loading(texte = () => <CircularProgress />) {
  toast.info(texte, {
    icon: false,
    draggable: true,
    autoClose: 5000,
    theme: "colored",
    closeButton: false,
    pauseOnHover: true,
    closeOnClick: true,
    progress: undefined,
    hideProgressBar: true,
    position: "bottom-right",
    className: "loading-toast",
    bodyClassName: "circular-toast"
  });
}
```

**Comment by lokomass** [comment]
thanks you very much !
